# configs/base.yaml
model:
  d_model: 512
  n_heads: 8
  n_layers: 6
  max_length: 256
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.001
  num_epochs: 20
  warmup_steps: 1000
  save_dir: "./checkpoints"

data:
  language: "id"
  min_text_length: 1000
  topics:
    - "Kecerdasan buatan"
    - "Pembelajaran mesin"
    - "Python"
    - "Ilmu komputer"
    - "Data science"
